concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "hw11-rakamin_todo-api-gitlab"
  url = "https://gitlab.com/"
  id = 29006283
  token = "xxkbVHse3ts6UY-VzCdx"
  token_obtained_at = 2023-10-28T15:22:54Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  [runners.cache]
    MaxUploadedArchiveSize = 0
