version: "3"

networks:
  app-tier:
    driver: bridge

services:
  hw11_todo-api_dev:
    build: .
    networks:
      - app-tier
    ports:
      - "3005:3005"
    depends_on:
      - pgsqldb
    volumes:
      - "./:/rakamin/homework/week11"
  pgsqldb:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - app-tier